bin_annotation_path: "/scratch/users/snarayanasamy/membrane_cleaning/output/annotation/test/bakta"
bins:
    - CBF1_MAGScoT_cleanbin_000016
    - CBF1_MAGScoT_cleanbin_000010
    - CBF1_MAGScoT_cleanbin_000005
