---
tmp_dir: "/tmp"
input_dir_binning: "/ibex/scratch/projects/c2188/membrane_cleaning"
output_dir: "/ibex/scratch/projects/c2188/membrane_cleaning/output"
input_dir_dereplication: "/ibex/scratch/projects/c2188/membrane_cleaning/output/binning"
sample_info: "/ibex/scratch/projects/c2188/membrane_cleaning/sample_info.txt"
mt_data_table: "/ibex/scratch/projects/c2188/membrane_cleaning/mt_sample_info.txt"
test_mt_data_table: "/ibex/scratch/projects/c2188/membrane_cleaning/test_mt_sample_info.txt"
bins_config: "config/bins_config.yml"
bin_annotation_path: "/ibex/scratch/projects/c2188/membrane_cleaning/output/annotation/all/bakta/"

magscot:
    folder: "/home/users/snarayanasamy/repositories/github/MAGScoT"        

conditions: 
    - all
    - control
    - treatment

drep:
    completeness: 75
    contamination: 25
    strain_heterogeneity_weight: 1
    P_ani: 0.9
    S_ani: 0.9

bakta:
    db_path: "/mnt/lscratch/users/snarayanasamy/bakta/db"

catbat:
    threads: 40
    db_path:
      gtdb: "/ibex/reference/KSL/cat/20231120/20231120_CAT_gtdb/db"
      nr: "/ibex/reference/KSL/cat/20231120/20231120_CAT_nr/db"
    tx_path:
      gtdb: "/ibex/reference/KSL/cat/20231120/20231120_CAT_gtdb/tax"
      nr: "/ibex/reference/KSL/cat/20231120/20231120_CAT_nr/tax"

trimmomatic:
    adapters_path: "/ibex/scratch/projects/c2188/membrane_cleaning/MT/adapters.fa"

sortmerna:
    db_path: "/scratch/users/snarayanasamy/sortmerna"

salmon:
    min_assigned_frags: 1

gtdbtk:
    db_path: "/ibex/reference/KSL/gtdb-tk/release214"
