---
tmp_dir: "/tmp"
input_dir_binning: "/scratch/users/snarayanasamy/membrane_cleaning"
input_dir_dereplication: "/scratch/users/snarayanasamy/membrane_cleaning/output"
output_dir: "/scratch/users/snarayanasamy/membrane_cleaning/output"
sample_info: "/scratch/users/snarayanasamy/membrane_cleaning/sample_info.txt"

magscot:
    folder: "/home/users/snarayanasamy/repositories/github/MAGScoT"        

conditions: 
    - all
    - control
    - treatment

drep:
    completeness: 75
    contamination: 25
    strain_heterogeneity_weight: 1
    P_ani: 0.9
    S_ani: 0.9

bakta:
    db_path: "/mnt/lscratch/users/snarayanasamy/bakta/db"

catbat:
    db_path: "/scratch/users/snarayanasamy/catbat/CAT_prepare_20210107/2021-01-07_CAT_database"
    tx_path: "/scratch/users/snarayanasamy/catbat/CAT_prepare_20210107/2021-01-07_taxonomy"

sortmerna:
    db_path: "/scratch/users/snarayanasamy/sortmerna/silva_ids_acc_tax"
