__default__:
    time: "0-01:00:00"
    partition: "batch"
    nodes: 1
    ntasks: 1
    ncpus: 1
    job-name: "{rule}"
    mail-user: "shaman.narayanasamy@uni.lu"
    output: "{rule}-{jobid}.log"
    error: "{rule}-{jobid}.err"
    qos: "normal"

magscot_marker_genes:
    ncpus: 12
    time: "1-00:00:00"

magscot_bin_refinement:
    ncpus: 6
    time: "1-00:00:00"

magscot_separate_bins:
    ncpus: 1
    time: "6:00:00"

drep_collect_all_bins:
    ncpus: 1
    time: "6:00:00"

drep_dereplication:
    ncpus: 16
    time: "2-00:00:00"
    partition: "bigmem"

bakta_annotation:
    nodes: 1
    ncpus: 12
    time: "48:00:00"

catbat_classification:
    nodes: 1
    ncpus: 24
    time: "48:00:00"
    partition: "bigmem"

catbat_summary:
    nodes: 1
    ncpus: 6
    time: "6:00:00"

trimmomatic_trimming:
    nodes: 1
    ncpus: 12
    time: "48:00:00"

index_all_transcripts:
    nodes: 1
    ncpus: 14
    time: "48:00:00"

salmon_quant_all:
    nodes: 1
    ncpus: 14
    time: "48:00:00"
